const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  visitedViews: state => state.app.visitedViews,
  cachedViews: state => state.app.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  username: state => state.user.username,
  introduction: state => state.user.introduction,
  status: state => state.user.status,
  roles: state => state.user.roles,
  menus: state => state.user.menus,
  elements: state => state.user.elements,
  setting: state => state.user.setting,
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  permissionMenus: state => state.user.permissionMenus,
  isEcho: state => state.app.isEcho, // 催收查询 催收业绩统计
  apprDetails: state => state.app.apprDetails, // 信审详情
  apprDetailsEnd: state => state.app.apprDetailsEnd, // 终审详情
  queryDetail: state => state.app.queryDetail, // 统计查询
  loanDetails: state => state.app.loanDetails, // 放款详情,
  editGroups: state => state.app.editGroups, // 编辑分组
  collDetails: state => state.app.collDetails, // 催收详情
  collQueryDetails: state => state.app.collQueryDetails, // 催收查询详情
  extDetails: state => state.app.extDetails, // 外催详情
  reduDetails: state => state.app.reduDetails, // 减免详情
  auditDetails: state => state.app.auditDetails, // 减免详情
  approvalPage: state => state.app.approvalPage, // 业务审批查询条件
  trustAchiPage: state => state.app.trustAchiPage, // 信审业绩统计
  apprDispPage: state => state.app.apprDispPage, // 信审查询
  confirmPage: state => state.app.confirmPage, // 业务审批确认
  orderPage: state => state.app.orderPage, // 订单查询
  lendersPage: state => state.app.lendersPage, // 业务放款
  processPage: state => state.app.processPage, // 催收业务处理
  groupPage: state => state.app.groupPage, // 催收分组管理
  collDispPage: state => state.app.collDispPage, // 催收查询
  collAchiPage: state => state.app.collAchiPage, // 催收业绩统计
  extPage: state => state.app.extPage, // 外催
  applyPage: state => state.app.applyPage, // 减免申请
  auditPage: state => state.app.auditPage, // 减免审核
  customPage: state => state.app.customPage, // 客服查询
  blackPage: state => state.app.blackPage, // 黑名单
  appVerPage: state => state.app.appVerPage, // 版本管理
  endReportPage: state => state.app.endReportPage, // 终审报表
  rushReportPage: state => state.app.rushReportPage, // 在催报表
  remindersPage: state => state.app.remindersPage, // 入催报表
  returnMonPage: state => state.app.returnMonPage // 回款报表
};
export default getters
